In [1]:
import pandas as pd

In [14]:
df_kobe = pd.read_parquet("../data/01_raw/dataset_kobe_dev.parquet")

In [15]:
df_kobe

,action_type,combined_shot_type,game_event_id,game_id,lat,loc_x,loc_y,lon,minutes_remaining,period,...,shot_type,shot_zone_area,shot_zone_basic,shot_zone_range,team_id,team_name,game_date,matchup,opponent,shot_id
0,Jump Shot,Jump Shot,10,20000012,33.9723,167,72,-118.1028,10,1,...,2PT Field Goal,Right Side(R),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,1
1,Jump Shot,Jump Shot,12,20000012,34.0443,-157,0,-118.4268,10,1,...,2PT Field Goal,Left Side(L),Mid-Range,8-16 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,2
2,Jump Shot,Jump Shot,35,20000012,33.9093,-101,135,-118.3708,7,1,...,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,3
3,Jump Shot,Jump Shot,43,20000012,33.8693,138,175,-118.1318,6,1,...,2PT Field Goal,Right Side Center(RC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,4
4,Driving Dunk Shot,Dunk,155,20000012,34.0443,0,0,-118.2698,6,2,...,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-10-31,LAL @ POR,POR,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30691,Driving Layup Shot,Layup,382,49900088,34.0443,0,0,-118.2698,7,4,...,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30692
30692,Jump Shot,Jump Shot,397,49900088,33.9963,1,48,-118.2688,6,4,...,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30693
30693,Tip Shot,Tip Shot,398,49900088,34.0443,0,0,-118.2698,6,4,...,2PT Field Goal,Center(C),Restricted Area,Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30694
30694,Running Jump Shot,Jump Shot,426,49900088,33.8783,-134,166,-118.4038,3,4,...,2PT Field Goal,Left Side Center(LC),Mid-Range,16-24 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30695
30696,Jump Shot,Jump Shot,471,49900088,33.9723,1,72,-118.2688,0,4,...,2PT Field Goal,Center(C),In The Paint (Non-RA),Less Than 8 ft.,1610612747,Los Angeles Lakers,2000-06-19,LAL vs. IND,IND,30697

In [16]:
columns = ["lat", "lon", "minutes_remaining", "period", "playoffs", "shot_distance", "shot_made_flag"]
df_kobe_filtered = df_kobe[columns]

In [17]:
df_kobe_filtered

,lat,lon,minutes_remaining,period,playoffs,shot_distance,shot_made_flag
0,33.9723,-118.1028,10,1,0,18,NaN
1,34.0443,-118.4268,10,1,0,15,0.0
2,33.9093,-118.3708,7,1,0,16,1.0
3,33.8693,-118.1318,6,1,0,22,0.0
4,34.0443,-118.2698,6,2,0,0,1.0
...,...,...,...,...,...,...,...
30691,34.0443,-118.2698,7,4,1,0,0.0
30692,33.9963,-118.2688,6,4,1,4,0.0
30693,34.0443,-118.2698,6,4,1,0,NaN
30694,33.8783,-118.4038,3,4,1,21,1.0
30696,33.9723,-118.2688,0,4,1,7,0.0

In [24]:
from pycaret.regression import setup, compare_models

exp_clf = setup(df_kobe_filtered, target='shot_made_flags')
best = compare_models(sort='MAE')

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 from pycaret.regression import setup, compare_models                                         │
│   2                                                                                              │
│   3 exp_clf = setup(df_kobe_filtered, target='shot_made_flags')                                  │
│   4 best = compare_models(sort='MAE')                                                            │
│                                                                                                  │
│ /home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-pa │
│ ckages/pycaret/regression/__init__.py:1 in <module>                                              │
│                                                                                                  │
│ ❱  1 from pycaret.regression.functional import (                                                 │
│    2 │   add_metric,                                                                             │
│    3 │   automl,                                                                                 │
│    4 │   blend_models,                                                                           │
│                                                                                                  │
│ /home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-pa │
│ ckages/pycaret/regression/functional.py:10 in <module>                                           │
│                                                                                                  │
│      7                                                                                           │
│      8 from pycaret.internal.parallel.parallel_backend import ParallelBackend                    │
│      9 from pycaret.loggers.base_logger import BaseLogger                                        │
│ ❱   10 from pycaret.regression.oop import RegressionExperiment                                   │
│     11 from pycaret.utils.constants import DATAFRAME_LIKE, SEQUENCE_LIKE, TARGET_LIKE            │
│     12 from pycaret.utils.generic import check_if_global_is_not_none                             │
│     13                                                                                           │
│                                                                                                  │
│ /home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-pa │
│ ckages/pycaret/regression/oop.py:23 in <module>                                                  │
│                                                                                                  │
│     20 # Own module                                                                              │
│     21 from pycaret.internal.pipeline import Pipeline as InternalPipeline                        │
│     22 from pycaret.internal.preprocess.preprocessor import Preprocessor                         │
│ ❱   23 from pycaret.internal.pycaret_experiment.non_ts_supervised_experiment import (            │
│     24 │   _NonTSSupervisedExperiment,                                                           │
│     25 )                                                                                         │
│     26 from pycaret.loggers.base_logger import BaseLogger                                        │
│                                                                                                  │
│ /home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-pa │
│ ckages/pycaret/internal/pycaret_experiment/non_ts_supervised_experiment.py:3 in <module>         │
│                                                                                                  │
│     1 import pandas as pd                                                                        │
│     2                                                                                            │
│ ❱   3 from pycaret.internal.pycaret_experiment.supervised_experiment import (                    │
│     4 │   _SupervisedExperiment,                                                                 │
│     5 )                                                                                          │
│     6                                                                                            │
│                                                                                                  │
│ /home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-pa │
│ ckages/pycaret/internal/pycaret_experiment/supervised_experiment.py:57 in <module>               │
│                                                                                                  │
│     54 │   get_pipeline_estimator_label,                                                         │
│     55 │   get_pipeline_fit_kwargs,                                                              │
│     56 )                                                                                         │
│ ❱   57 from pycaret.internal.pycaret_experiment.tabular_experiment import _TabularExperiment     │
│     58 from pycaret.internal.tunable import TunableMixin                                         │
│     59 from pycaret.internal.validation import is_fitted, is_sklearn_cv_generator                │
│     60 from pycaret.utils._dependencies import _check_soft_dependencies                          │
│                                                                                                  │
│ /home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-pa │
│ ckages/pycaret/internal/pycaret_experiment/tabular_experiment.py:14 in <module>                  │
│                                                                                                  │
│     11 import numpy as np  # type: ignore                                                        │
│     12 import pandas as pd                                                                       │
│     13 import plotly.express as px  # type: ignore                                               │
│ ❱   14 import scikitplot as skplt  # type: ignore                                                │
│     15 from IPython.display import display as ipython_display                                    │
│     16 from joblib.memory import Memory                                                          │
│     17 from packaging import version                                                             │
│                                                                                                  │
│ /home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-pa │
│ ckages/scikitplot/__init__.py:2 in <module>                                                      │
│                                                                                                  │
│   1 from __future__ import absolute_import, division, print_function, unicode_literals           │
│ ❱ 2 from . import metrics, cluster, decomposition, estimators                                    │
│   3 __version__ = '0.3.7'                                                                        │
│   4                                                                                              │
│   5                                                                                              │
│                                                                                                  │
│ /home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-pa │
│ ckages/scikitplot/metrics.py:27 in <module>                                                      │
│                                                                                                  │
│     24 from sklearn.calibration import calibration_curve                                         │
│     25 from sklearn.utils import deprecated                                                      │
│     26                                                                                           │
│ ❱   27 from scipy import interp                                                                  │
│     28                                                                                           │
│     29 from scikitplot.helpers import binary_ks_curve, validate_labels                           │
│     30 from scikitplot.helpers import cumulative_gain_curve                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'interp' from 'scipy'
(/home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-packages/scipy/__ini
t__.py)

In [25]:
from scipy import interp

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 from scipy import interp                                                                     │
│   2                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'interp' from 'scipy'
(/home/bakudas/code/INFNET_POS/pos-infnet-eng-machine-learning/.venv-engML/lib/python3.11/site-packages/scipy/__ini
t__.py)